<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Error hukumonline</title>
  <link href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" rel="shortcut icon" type="image/ico" />
  <link href="<?=$this->baseUrl();?>/resources/css/elastic.css" media="screen" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery/jquery-1.4.2.min"></script>
</head>
<body>
    <div class="container">
        <div class="unit horizontal-center layout" style="padding:10px;">
            <h1>An error occurred</h1>
            <h2><?php echo $this->message ?></h2>

            <?php if (isset($this->exception)): ?>

            <h3>Exception information:</h3>
            <p>
              <b>Message:</b> <?php echo $this->exception->getMessage() ?>
            </p>

            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?>
            </pre>

            <h3>Request Parameters:</h3>
            <pre><?php echo var_export($this->request->getParams(), true) ?>
            </pre>
            <?php endif ?>
        </div>
    </div>
</body>
</html>
